/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libreria;

import java.awt.Color;

/**
 *
 * @author Walter
 */
public class interfazLibreria extends javax.swing.JFrame {

    /**
     * Creates new form interfazLibreria
     */
    public interfazLibreria() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Libreria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        lblLibreria0 = new javax.swing.JLabel();
        lblLibreria = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jContraseña = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        lblRegistrarse = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(153, 255, 204));
        jPanelPrincipal.setForeground(new java.awt.Color(51, 51, 51));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLibreria0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria.png"))); // NOI18N
        jPanelPrincipal.add(lblLibreria0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblLibreria.setForeground(new java.awt.Color(102, 255, 153));
        lblLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria.png"))); // NOI18N
        jPanelPrincipal.add(lblLibreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 6, -1, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre.setText("LIBRERIA TODO A SU SERVICIO");
        jPanelPrincipal.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 28, -1, 33));

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        jPanelPrincipal.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 79, 135, -1));

        lblSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblSesion.setText("INICIAR SESIÓN");
        jPanelPrincipal.add(lblSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 213, 154, 30));

        lblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario.setText("USUARIO");
        jPanelPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 261, 66, 27));

        txtUsuario.setBackground(new java.awt.Color(153, 255, 204));
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setText("Ingrese su nombre de Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 294, 225, 27));
        jPanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 327, 262, 10));

        lblContraseña.setBackground(new java.awt.Color(0, 0, 0));
        lblContraseña.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblContraseña.setText("CONTRASEÑA");
        jPanelPrincipal.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 355, -1, 27));
        jPanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 415, 262, 10));

        jContraseña.setBackground(new java.awt.Color(153, 255, 204));
        jContraseña.setForeground(new java.awt.Color(51, 51, 51));
        jContraseña.setText("****************");
        jContraseña.setBorder(null);
        jContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jContraseñaMousePressed(evt);
            }
        });
        jContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContraseñaActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 394, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lblRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        lblRegistrarse.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblRegistrarse.setText("REGISTRARSE");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 437, -1, -1));

        btnCambiar.setBackground(new java.awt.Color(0, 204, 204));
        btnCambiar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnCambiar.setText("Ingresar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
    if(txtUsuario.getText().equals("Ingrese su nombre de Usuario")){
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.black);
    }
    if(String.valueOf(jContraseña.getPassword()).isEmpty()){
        jContraseña.setText("****************");
        jContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContraseñaActionPerformed
        
    }//GEN-LAST:event_jContraseñaActionPerformed

    private void jContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jContraseñaMousePressed
    if(String.valueOf(jContraseña.getPassword()).equals("****************")){
        jContraseña.setText("");
        jContraseña.setForeground(Color.black);
        
    }
    if(txtUsuario.getText().isEmpty()){
        txtUsuario.setText("Ingrese su nombre de Usuario");
        txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jContraseñaMousePressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        libreriaTodo libreria2 = new libreriaTodo();
        libreria2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JPasswordField jContraseña;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblLibreria;
    private javax.swing.JLabel lblLibreria0;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistrarse;
    private javax.swing.JLabel lblSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
