/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libreria;

import java.util.Calendar;

/**
 *
 * @author Walter
 */
public class libreriaTodo extends javax.swing.JFrame {

    /**
     * Creates new form libreriaTodo
     */
    public libreriaTodo() {
        initComponents();
        this.setLocationRelativeTo(null);
        Calendar cal = Calendar.getInstance();
        String fecha, hora;
        fecha = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
        hora = cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
        this.lblFecha1.setText(fecha);
        this.lblHora1.setText(hora);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblNombre1 = new javax.swing.JLabel();
        lblLibreria = new javax.swing.JLabel();
        lblLibreria1 = new javax.swing.JLabel();
        lblPrincipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblHora1 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblIntroduccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(204, 255, 204));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("LIBRERIA TODO A SU SERVICIO");
        panel.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 33));

        lblLibreria.setForeground(new java.awt.Color(102, 255, 153));
        lblLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria.png"))); // NOI18N
        panel.add(lblLibreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, 110));

        lblLibreria1.setForeground(new java.awt.Color(102, 255, 153));
        lblLibreria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libreria.png"))); // NOI18N
        panel.add(lblLibreria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/7133267.png"))); // NOI18N
        panel.add(lblPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 56, 43));

        jList1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pincipal", "Prestamos Libros", "Devoluciones", "Usuarios", "Libros", "Venta de Libros", "Reporte", "Facturas", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 150));

        lblFecha.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lblFecha.setText("FECHA");
        panel.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        lblHora.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHora.setText("HORA");
        panel.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        lblHora1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblHora1.setText("00:00:00");
        panel.add(lblHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 90, -1));

        lblFecha1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        lblFecha1.setText("00/00/00");
        panel.add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, -1));

        lblIntroduccion.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        lblIntroduccion.setText("Bienvenido");
        panel.add(lblIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 89, 26));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Sistema Virtual de Gestion para libreria Virtual.\nLa cuál permitira controlar y administrar de forma óptica \ny fácil lo que es préstamo, devoluciones y compra de libros\nEste sistema permirira llevar un control detallado de la libreria\n\nLos cuáles son:\n\n* Préstamos\n* Devoluciones\n* Registro y Edicion de Usuario y Nuevos Libros\n* Sección de Reporte de Ventas\n");
        jScrollPane2.setViewportView(jTextArea1);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 440, 230));

        btnCambiar.setBackground(new java.awt.Color(255, 255, 204));
        btnCambiar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnCambiar.setText("Factura");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        panel.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        datosFactura dFactura = new datosFactura();
        dFactura.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libreriaTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libreriaTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libreriaTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libreriaTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libreriaTodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblHora1;
    private javax.swing.JLabel lblIntroduccion;
    private javax.swing.JLabel lblLibreria;
    private javax.swing.JLabel lblLibreria1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
